*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
INCLUDE LZPR_FGV01 .

FUNCTION $$UNIT$$ Z_PR_CREATE_DATA

    IMPORTING
       VALUE(I_WTKT) TYPE !ZPR_DT_WTKTNO OPTIONAL
       VALUE(I_WTKTITEM) TYPE !ZPR_DT_WTKTITM OPTIONAL
    EXPORTING
       VALUE(E_RETURN) TYPE !CHAR1 .