CLASS LCL_INSPECTIONLOT_CANCELED_V1 DEFINITION FINAL INHERITING FROM /IWXBE/CL_ABS_CONSUMER_EVENT.
  PUBLIC SECTION.
    INTERFACES:
      ZPRIF_INSPECTIONLOT_CANCE_ACF8.

ENDCLASS.

CLASS LCL_INSPECTIONLOT_CANCELED_V1 IMPLEMENTATION.
  METHOD ZPRIF_INSPECTIONLOT_CANCE_ACF8~GET_BUSINESS_DATA.
      mo_event->get_business_data( IMPORTING es_business_data = rs_business_data ).
  ENDMETHOD.
ENDCLASS.
CLASS LCL_INSPECTIONLOT_CHANGED_V1 DEFINITION FINAL INHERITING FROM /IWXBE/CL_ABS_CONSUMER_EVENT.
  PUBLIC SECTION.
    INTERFACES:
      ZPRIF_INSPECTIONLOT_CHANGED_V1.

ENDCLASS.

CLASS LCL_INSPECTIONLOT_CHANGED_V1 IMPLEMENTATION.
  METHOD ZPRIF_INSPECTIONLOT_CHANGED_V1~GET_BUSINESS_DATA.
      mo_event->get_business_data( IMPORTING es_business_data = rs_business_data ).
  ENDMETHOD.
ENDCLASS.
CLASS LCL_INSPECTIONLOT_CREATED_V1 DEFINITION FINAL INHERITING FROM /IWXBE/CL_ABS_CONSUMER_EVENT.
  PUBLIC SECTION.
    INTERFACES:
      ZPRIF_INSPECTIONLOT_CREATED_V1.

ENDCLASS.

CLASS LCL_INSPECTIONLOT_CREATED_V1 IMPLEMENTATION.
  METHOD ZPRIF_INSPECTIONLOT_CREATED_V1~GET_BUSINESS_DATA.
      mo_event->get_business_data( IMPORTING es_business_data = rs_business_data ).
  ENDMETHOD.
ENDCLASS.
CLASS LCL_INSPECTIONLOT_OPERATI_E07B DEFINITION FINAL INHERITING FROM /IWXBE/CL_ABS_CONSUMER_EVENT.
  PUBLIC SECTION.
    INTERFACES:
      ZPRIF_INSPECTIONLOT_OPERA_894A.

ENDCLASS.

CLASS LCL_INSPECTIONLOT_OPERATI_E07B IMPLEMENTATION.
  METHOD ZPRIF_INSPECTIONLOT_OPERA_894A~GET_BUSINESS_DATA.
      mo_event->get_business_data( IMPORTING es_business_data = rs_business_data ).
  ENDMETHOD.
ENDCLASS.